name: rnaseq
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - fastp=0.19.4
  - bwa=0.7.17
  - samtools=1.9
  - csvtk=0.18.2
  - porechop=0.2.3_seqan2.1.1
  - graphmap=0.5.2
  - minimap2=2.17
