dataset: CPm
fq_dir: /vol/projects/dzhiluo/Pminimum/data/seq
out_dir: /vol/projects/dzhiluo/Pminimum/outputs
ref: /vol/projects/dzhiluo/Pminimum/ref/Prorocentrum-minimum-CCMP1329.cds.fa
ref_pep: /vol/projects/dzhiluo/Pminimum/ref/Prorocentrum-minimum-CCMP1329.cds.fa
kegg: /vol/projects/dzhiluo/dbs/kegg/kegg/genes/fasta/family_eukaryotes.pep
gene_ko_map: /vol/projects/dzhiluo/dbs/kegg/genes_ko.list
kofamscan: /vol/projects/dzhiluo/dbs/kegg/kofamscan/bin


# Path to your KO-HMM database
# A database can be a .hmm file, a .hal file or a directory in which
# .hmm files are. Omit the extension if it is .hal or .hmm file
profile: /vol/projects/dzhiluo/dbs/kegg/kofamscan/db/profiles

# Path to the KO list file
ko_list: /vol/projects/dzhiluo/dbs/kegg/kofamscan/db/ko_list

threads: 20